import { Nunito_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import ThemeProvider from "@/components/general/theme-proivder";
import StoreProvider from "./store-provider";
import LoadingProgressBar from "@/components/general/loading-progress-bar";
import React from "react";

export const metadata = {
  title: "DashStack",
  description: "Generated by create next app",
};

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={cn(
          "grid-main bg-background font-sans antialiased",
          nunito_sans.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <StoreProvider>
            <LoadingProgressBar>{children}</LoadingProgressBar>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
