import React from "react";
import { Nunito_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import Navbar from "@/components/general/nav/navbar";
import Header from "@/components/general/header";
import ThemeProvider from "@/components/general/theme-proivder";
import "@/app/globals.css";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    // <html lang="en">
    //   <body
    //     className={cn(
    //       "grid-main min-h-screen bg-background font-sans antialiased",
    //       nunito_sans.variable,
    //     )}
    //   >
    //     <ThemeProvider
    //       attribute="class"
    //       defaultTheme="system"
    //       enableSystem
    //       disableTransitionOnChange
    //     >
    <>
      <Header />
      <Navbar />
      <main className="main-position bg-gray-100 p-8 dark:bg-dark-100">
        {children}
      </main>
    </>
    //     </ThemeProvider>
    //   </body>
    // </html>
  );
};

export default RootLayout;
