import React from "react";
import { Nunito_Sans } from "next/font/google";
import { cn } from "@/lib/utils";
import ThemeProvider from "@/components/general/theme-proivder";
import "@/app/globals.css";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          nunito_sans.variable,
        )}
      >
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
