import Navbar from "@/components/general/navbar";
import Header from "@/components/general/header";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <Navbar />
      <main className="main-position bg-gray-100 p-8 dark:bg-dark-100">
        {children}
      </main>
    </>
  );
}
