import Navbar from "@/components/general/nav/navbar";
import Header from "@/components/general/header";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Header />
      <Navbar />
      <main className="main-position relative rounded-xl bg-gray-100 p-8 dark:bg-dark-100 md:ml-3">
        {children}
      </main>
    </>
  );
}
